version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.service
    ports:
    - 8083:8083
    volumes:
    - ./lib:/opt/klot-io/lib
    - ./bin:/opt/klot-io/bin
    - /Volumes/boot/klot-io/config:/opt/klot-io/config/
  gui:
    build:
      context: .
      dockerfile: Dockerfile.gui
    depends_on:
    - api
    ports:
    - 8084:80
    volumes:
    - ./etc/docker.conf:/etc/nginx/conf.d/default.conf
    - ./www:/opt/klot-io/www
