apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: apps.klot.io
spec:
  group: klot.io
  version: v1
  versions:
    - name: v1
      served: true
      storage: true
  scope: Cluster
  names:
    plural: apps
    singular: app
    kind: App
